import faker from '@faker-js/faker';
import { FC, useMemo } from 'react';
import { Helmet } from '../Helmet/Helmet.styled';
import { LoadableImage } from '../LoadableImage/LoadableImage.component';
import { usePageStackRouter } from '../PageStackRouter';
import { Profile } from './Profile.styled';

interface ProfileProps {
  name: string;
}

const ProfileComponent: FC<ProfileProps> = (props) => {
  // random phone number generated by faker
  const phoneNumber = useMemo(() => faker.phone.phoneNumber(), []);
  const avatarImg = useMemo(() => faker.image.avatar(), []);
  const email = useMemo(() => faker.internet.email(), []);
  const { pop } = usePageStackRouter();

  return (
    <Profile.Container>
      <Helmet.Container>
        <Helmet.Left onClick={pop}>Contacts</Helmet.Left>
        <Helmet.Title>{props.name}</Helmet.Title>
        <Helmet.Right>Edit</Helmet.Right>
      </Helmet.Container>
      <Profile.Avatar.Container>
        <LoadableImage
          src={avatarImg}
          style={{
            height: '6rem',
            width: '6rem',
            borderRadius: '50%',
          }}
        />
        <Profile.Avatar.Label>{props.name}</Profile.Avatar.Label>
      </Profile.Avatar.Container>
      <Profile.Phone.Container>
        <Profile.Phone.Label>Phone</Profile.Phone.Label>
        <Profile.Phone.Number>{phoneNumber}</Profile.Phone.Number>
      </Profile.Phone.Container>
      <Profile.Email.Container>
        <Profile.Email.Label>Email</Profile.Email.Label>
        <Profile.Email.Address>{email}</Profile.Email.Address>
      </Profile.Email.Container>
      <Profile.Notes.Container>
        <Profile.Notes.Label>Notes</Profile.Notes.Label>
        <Profile.Notes.Text></Profile.Notes.Text>
      </Profile.Notes.Container>
    </Profile.Container>
  );
};

export { ProfileComponent };
